### ISSUE TITLE
GM_xmlhttpRequest is not defined

### ISSUE THREAD

**Issue by makise-homura** [stsyn/random-stuff#1]
While using `helloFromBackup.user.js`, I got the following error:
```
Script error in [Greasemonkey скрипт raw.githubusercontent.com/Two tabuns in one; версия 0.2]:
ReferenceError: GM_xmlhttpRequest is not defined Two tabuns in one:291:19
    <анонимный> user-script:raw.githubusercontent.com/Two tabuns in one:291
```
Firefox 84.0, Greasemonkey 4.10.0.

For me, it works if I just replace `GM_xmlhttpRequest` to `GM.xmlHttpRequest` (case sensitive!) in `@grant` and `getPostFromMirror()`, like [suggested here](https://stackoverflow.com/questions/49365651/greasemonkey-gm-xmlhttprequest-is-not-defined-with-the-new-update); but you may want to fix it using more portable way to support Greasemonkey < 4.0.

**Comment by stsyn** [comment]
It's kinda moronic to make breaking changes without keeping backwards compatibility with literally everything, including alternative userscripts managers.

Updated script, please check, if this helped.

**Comment by makise-homura** [comment]
Yeah, now it works. Guess there is some way to distinguish between `GM_xmlhttpRequest` and `GM.xmlHttpRequest` existense? Like `typeof(GM_xmlhttpRequest) == "function"` or whatever.

**Comment by makise-homura** [comment]
Oops, not quite, in 0.4 is has been broken again, but the fix is obvious, use `@grant GM.xmlHttpRequest` instead of `@grant GM.xmlhttpRequest` (somehow case does matter here)

**Comment by stsyn** [comment]
Fixed

**Comment by makise-homura** [comment]
Yeah, now everything is ok. Thanks!
