### ISSUE TITLE
helloFromBackup probably doesn't work on single deleted comment threads

### ISSUE THREAD

**Issue by makise-homura** [stsyn/random-stuff#4]
Specifically, it doesn't work for me [here](https://tabun.everypony.ru/blog/apc/198899.html) (see first and only comment).
Windows 7, Firefox 84.0.1, Greasemonkey 4.10.0, script 0.5.
No suspicious messages in console.

Actually, `Network` page shows a XHR request to `https://tabun.andreymal.org/comments/replies/?empty=1&token=...` (note: there's no post id!), with the following response contents:
```
{"last_id": null, "last_readed_id": 2553057, "html": "", "command": "replies", "new_count": 0}
```
but comment is not even empty [here](https://tabun.andreymal.org/blog/apc/198899.html).
I guess this XHR has nothing to do with your script anyways, it's more like to be from Tabun Replies script.

**Comment by stsyn** [comment]
Issue was with querySelector, missing this particular comment. Should be fixed

**Comment by makise-homura** [comment]
Thanks! Now it works.
Also I consider updating script version number, for Greasemonkey/Tampermonkey update being able to pull updated version.
